# Gelistirme ortami profili - detayli loglama, mock/ucretsiz email saglayici
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace



# Dev ortaminda schema degisiklikleri otomatik uygulanir
spring.jpa.hibernate.ddl-auto=update

# Dev ortaminda ucretsiz/mock email saglayicisi kullanilir
email.service=turkcell

management.endpoint.health.show-details=always
